Vagrant.configure("2") do |config|

  config.vm.define "scriptbox" do |scriptbox|
    scriptbox.vm.box = "eurolinux-vagrant/centos-stream-9"
      scriptbox.vm.box_version = "9.0.45"
  	  scriptbox.vm.hostname = "scriptbox"
  	  scriptbox.vm.network "private_network", ip: "192.168.56.16"
  end

    config.vm.define "web01" do |web01|
    web01.vm.box = "eurolinux-vagrant/centos-stream-9"
      web01.vm.box_version = "9.0.45"
	    web01.vm.network "private_network", ip: "192.168.56.3"
      web01.vm.hostname = "web01"
  end
  
  config.vm.define "web02" do |web02|
    web02.vm.box = "eurolinux-vagrant/centos-stream-9"
      web02.vm.box_version = "9.0.45"
	    web02.vm.network "private_network", ip: "192.168.56.4"
      web02.vm.hostname = "web02"
  end
  
  config.vm.define "web03" do |web03|
    web03.vm.box = "ubuntu/xenial64"
	    web03.vm.network "private_network", ip: "192.168.56.5"
      web03.vm.hostname = "web03"
  end
end
